CLASS zcl_event_um_test DEFINITION
  PUBLIC
  FINAL for EVENTS OF zi_um_head
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_EVENT_UM_TEST IMPLEMENTATION.
ENDCLASS.
